### ISSUE TITLE
Can not access Datasets

### ISSUE THREAD

**Issue by TianhangWang** [GT-RIPL/MultiAgentPerception#1]
Hi, can you show me how to access your AirSim-MAP datasets? I only got 404 not found error message back. Thanks a lot!

**Comment by ycliu93** [comment]
Just renew the access. Please check the link again. 

Thanks

**Comment by TianhangWang** [comment]
Thanks! Now it's available!

**Comment by JasonHysy** [comment]
Hi! sorry to bother you again. The link to the dataset has expired. Can you please renew it again? Thanks a lot!

**Comment by ycliu93** [comment]
Thanks for letting me know. I just renew the access. Please check the link again. (Sorry it has to be manually renewed every three months)

**Comment by JasonHysy** [comment]
It's available now! Thanks for renewing it :)

**Comment by lubin2022** [comment]
Hello! The link to the dataset has expired. Could you please renew it again? Thanks a lot!

**Comment by ycliu93** [comment]
Extended it to Jan. 2nd 2023. Thanks for the reminder!

**Comment by lubin2022** [comment]
It's available now! Thanks a lot!

**Comment by codeck313** [comment]
Hi I think it has again expired, could you please renew it again.

**Comment by wwwwwait** [comment]
Hello the link has expired again, Could you please renew it again? Thanks so much
